[global]
log_level = "info"
max_parallel = 4
output_dir = ".task-logs"

[tasks.install]
command = "yarn install"
description = "Install dependencies"
parsers = ["yarn-install", "npm-dedupe"]
watch_files = ["package.json", "yarn.lock"]
auto_restart = false

[tasks.dev]
command = "yarn dev"
description = "Start Next.js dev server"  
parsers = ["nextjs", "webpack-dev"]
depends_on = ["install"]
auto_restart = true
port_check = 3000

[tasks.build]
command = "yarn build"
parsers = ["nextjs-build", "typescript"]
env = { NODE_ENV = "production" }

[tasks.nx-serve]
command = "npx nx serve my-app"
parsers = ["nx-serve", "webpack-dev"]
depends_on = ["install"]

# Parser configurations
[parsers.yarn-install]
patterns = [
  { regex = "warning (.+)", level = "warn", extract = "message" },
  { regex = "error (.+)", level = "error", extract = "message" },
  { regex = "✨  Done in (.+)s", level = "success", extract = "duration" }
]

[parsers.nextjs]
patterns = [
  { regex = "ready - started server on.+", level = "success" },
  { regex = "event - compiled (.+)", level = "info", extract = "status" },
  { regex = "wait  - compiling", level = "info" }
]
