[global]
log_level = "info"
max_parallel = 4
output_dir = ".task-logs"

[tasks.install]
command = "yarn install"
description = "Install dependencies"
parsers = ["yarn-install"]
watch_files = ["package.json", "yarn.lock"]
auto_restart = false

# Parser configurations
[parsers.yarn-install]
patterns = [
  { regex = "warning (.+)", level = "warn", extract = "message" },
  { regex = "error (.+)", level = "error", extract = "message" },
  { regex = "✨  Done in (.+)s", level = "success", extract = "duration" }
]

